"""Multiplicative subgroups and cosets over F_p.

p = 3 * 2**30 + 1 means F_p* has order 3 * 2**30, so it contains a
2-Sylow subgroup of order 2**30. The `blowup_domain` helper returns a
coset of that subgroup (shifted so it never collides with the
subgroup itself) — needed for low-degree extension and FRI pairing.
"""

from __future__ import annotations

from stark_fibonacci.field import FIELD_PRIME, FieldElement


_PRIMITIVE_ROOT_CACHE: FieldElement | None = None


def _find_primitive_root() -> FieldElement:
    """Find a primitive root of F_p* (order exactly p-1).

    For p-1 = 3 * 2**30 an element r is primitive iff
        r**((p-1)/2) != 1 and r**((p-1)/3) != 1,
    i.e. it is neither a square nor a cube.
    """
    global _PRIMITIVE_ROOT_CACHE
    if _PRIMITIVE_ROOT_CACHE is not None:
        return _PRIMITIVE_ROOT_CACHE
    half = (FIELD_PRIME - 1) // 2
    third = (FIELD_PRIME - 1) // 3
    for candidate in (
        2,
        3,
        5,
        7,
        11,
        13,
        17,
        19,
        23,
        29,
        31,
        37,
        41,
        43,
        47,
        53,
        59,
        61,
        67,
        71,
        73,
        79,
        83,
        89,
        97,
        127,
        257,
        1021,
    ):
        r = FieldElement(candidate)
        if r**half != 1 and r**third != 1:
            _PRIMITIVE_ROOT_CACHE = r
            return r
    raise RuntimeError("no primitive root of F_p* found for this prime")


def primitive_root_of_unity(order: int) -> FieldElement:
    """Return a primitive order-`order` element of F_p, i.e. an element
    whose multiplicative order is exactly `order`.
    """
    if order <= 0:
        raise ValueError("order must be a positive integer")
    if (FIELD_PRIME - 1) % order != 0:
        raise ValueError(f"order {order} does not divide p-1 = {FIELD_PRIME - 1}")
    r = _find_primitive_root()
    g = r ** ((FIELD_PRIME - 1) // order)
    if g**order != FieldElement.one():
        raise RuntimeError("internal: g**order != 1, primitive root lookup failed")
    return g


def multiplicative_subgroup(size: int) -> list[FieldElement]:
    """Return the multiplicative subgroup of given `size` as
    [1, g, g^2, ..., g**(size-1)] where g has exact order `size`.
    """
    if size <= 0:
        raise ValueError("size must be a positive integer")
    if (FIELD_PRIME - 1) % size != 0:
        raise ValueError(f"size {size} does not divide p-1 = {FIELD_PRIME - 1}")
    g = primitive_root_of_unity(size)
    domain: list[FieldElement] = []
    val = FieldElement.one()
    for _ in range(size):
        domain.append(val)
        val = val * g
    if len({x.value for x in domain}) != size:
        raise RuntimeError("subgroup contains duplicates")
    for x in domain:
        if x**size != 1:
            raise RuntimeError("subgroup element fails x**size == 1")
    return domain


def blowup_domain(base_size: int, blowup_factor: int) -> list[FieldElement]:
    """Return a coset of size `base_size * blowup_factor`.

    The coset is generated by a primitive order-`N` element with a shift
    taken as a primitive root of F_p* (so the shift is never in the
    subgroup of order N, ensuring the coset is disjoint from the
    subgroup).
    """
    if base_size <= 0 or blowup_factor <= 0:
        raise ValueError("sizes must be positive")
    n = base_size * blowup_factor
    if (FIELD_PRIME - 1) % n != 0:
        raise ValueError(f"blowup size {n} does not divide p-1 = {FIELD_PRIME - 1}")
    g = primitive_root_of_unity(n)
    shift = _find_primitive_root()
    domain: list[FieldElement] = []
    val = shift
    for _ in range(n):
        domain.append(val)
        val = val * g
    return domain
